const posts = [
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/ancoustic-nest-pet-panel-1.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/uni-spares.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/ambrosia-beekeeping-academy-2.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/anaansh.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/anp-bee-1.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/atlas-rolling-1.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/bweld.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/celestial.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/cmed.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/comfort-2.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/dicocon-gel-25.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/gutaderme.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/envirotech-1.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/felicity.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/galaxy.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/ganesh-sky-balloon.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/gemak.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/glow-green.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/indian-roller.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/gemak-2.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/micro-industry.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/my-brand-please.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/nexus.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/poly-pack.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/radicon.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/refer-me.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/regent.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/shree-ram-2.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/smd-1.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/sports-barrel.webp",
  "https://jaikvik.in/lab/cloud/jaikvik/assets/images/social_media_image/uni-spares-2.webp",
];

export default posts;
