// src/configs/all-blogs-data.ts
import type blogInterface from "../interfaces/blogInterface";

const blogs: blogInterface[] = [
  {
    id: "unlocking-growth-with-instagram-reels-in-2025",
    category: "Social Media Marketing",
    author: "Admin",
    date: "10 Jan 2025",
    title: "Unlocking Growth with Instagram Reels in 2025",
    description: "Instagram Reels are dominating social media. Learn how to leverage them for brand visibility, engagement, and explosive growth in 2025.",
    summary: "Instagram Reels are dominating social media. Learn how to leverage them for brand visibility...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "top-seo-trends-to-watch-in-2025",
    category: "SEO",
    author: "Admin",
    date: "15 Jan 2025",
    title: "Top SEO Trends to Watch in 2025",
    description: "Stay ahead with the latest SEO strategies shaping search engine rankings this year...",
    summary: "Stay ahead with the latest SEO strategies shaping search engine rankings this year...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "why-progressive-web-apps-are-the-future",
    category: "Website Development",
    author: "Admin",
    date: "20 Jan 2025",
    title: "Why Progressive Web Apps Are the Future",
    description: "Explore how PWAs enhance user experience and boost business performance...",
    summary: "Explore how PWAs enhance user experience and boost business performance...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/web.png",
  },
  {
    id: "advanced-ppc-techniques-for-maximum-roi",
    category: "PPC Advertising",
    author: "Admin",
    date: "25 Jan 2025",
    title: "Advanced PPC Techniques for Maximum ROI",
    description: "Master the art of Pay-Per-Click with cutting-edge strategies for 2025...",
    summary: "Master the art of Pay-Per-Click with cutting-edge strategies for 2025...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/ppc.jpg",
  },
  {
    id: "how-to-create-content-that-converts",
    category: "Content Marketing",
    author: "Admin",
    date: "01 Feb 2025",
    title: "How to Create Content That Converts",
    description: "Turn readers into customers with compelling content strategies...",
    summary: "Turn readers into customers with compelling content strategies...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "building-a-loyal-audience-on-linkedin",
    category: "Social Media Marketing",
    author: "Admin",
    date: "05 Feb 2025",
    title: "Building a Loyal Audience on LinkedIn",
    description: "Unlock LinkedIn’s potential to grow your professional network and brand...",
    summary: "Unlock LinkedIn’s potential to grow your professional network and brand...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "the-ultimate-guide-to-ecommerce-seo-success",
    category: "E-Commerce SEO",
    author: "Admin",
    date: "10 Feb 2025",
    title: "The Ultimate Guide to E-Commerce SEO Success",
    description: "Boost online sales with SEO tactics tailored for e-commerce platforms...",
    summary: "Boost online sales with SEO tactics tailored for e-commerce platforms...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/The Ultimate guide.png",
  },
  {
    id: "how-voice-search-is-changing-seo",
    category: "SEO",
    author: "Admin",
    date: "15 Feb 2025",
    title: "How Voice Search is Changing SEO",
    description: "Adapt your SEO strategy for the rise of voice-activated devices...",
    summary: "Adapt your SEO strategy for the rise of voice-activated devices...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/why.png",
  },
  {
    id: "ai-in-digital-marketing-the-next-big-thing",
    category: "Digital Marketing",
    author: "Admin",
    date: "20 Feb 2025",
    title: "AI in Digital Marketing: The Next Big Thing",
    description: "Discover how AI tools are revolutionizing ad targeting and customer engagement...",
    summary: "Discover how AI tools are revolutionizing ad targeting and customer engagement...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "personalized-emails-boosting-open-rates",
    category: "Email Marketing",
    author: "Admin",
    date: "25 Feb 2025",
    title: "Personalized Emails: Boosting Open Rates",
    description: "Learn how personalization can transform your email marketing campaigns...",
    summary: "Learn how personalization can transform your email marketing campaigns...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "using-google-analytics-for-smarter-decisions",
    category: "Analytics",
    author: "Admin",
    date: "01 Mar 2025",
    title: "Using Google Analytics for Smarter Decisions",
    description: "Unlock insights from your data to refine your marketing strategy...",
    summary: "Unlock insights from your data to refine your marketing strategy...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "building-a-strong-brand-identity-online",
    category: "Branding",
    author: "Admin",
    date: "05 Mar 2025",
    title: "Building a Strong Brand Identity Online",
    description: "Create a lasting impression with a cohesive digital brand presence...",
    summary: "Create a lasting impression with a cohesive digital brand presence...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "why-video-content-is-king-in-2025",
    category: "Video Marketing",
    author: "Admin",
    date: "10 Mar 2025",
    title: "Why Video Content is King in 2025",
    description: "Engage audiences with powerful video marketing strategies...",
    summary: "Engage audiences with powerful video marketing strategies...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "winning-local-customers-with-seo",
    category: "Local SEO",
    author: "Admin",
    date: "15 Mar 2025",
    title: "Winning Local Customers with SEO",
    description: "Dominate your local market with targeted SEO techniques...",
    summary: "Dominate your local market with targeted SEO techniques...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "choosing-the-right-influencers-for-your-brand",
    category: "Influencer Marketing",
    author: "Admin",
    date: "20 Mar 2025",
    title: "Choosing the Right Influencers for Your Brand",
    description: "Maximize ROI by partnering with influencers who align with your goals...",
    summary: "Maximize ROI by partnering with influencers who align with your goals...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "mastering-tiktok-ads-for-business-growth",
    category: "Social Media Marketing",
    author: "Admin",
    date: "25 Mar 2025",
    title: "Mastering TikTok Ads for Business Growth",
    description: "Tap into TikTok’s massive audience with effective ad campaigns...",
    summary: "Tap into TikTok’s massive audience with effective ad campaigns...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "link-building-strategies-that-work-in-2025",
    category: "SEO",
    author: "Admin",
    date: "01 Apr 2025",
    title: "Link Building Strategies That Work in 2025",
    description: "Boost your site’s authority with modern link-building tactics...",
    summary: "Boost your site’s authority with modern link-building tactics...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "speed-optimization-for-better-user-experience",
    category: "Website Development",
    author: "Admin",
    date: "05 Apr 2025",
    title: "Speed Optimization for Better User Experience",
    description: "Learn why site speed matters and how to optimize it effectively...",
    summary: "Learn why site speed matters and how to optimize it effectively...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/web.png",
  },
  {
    id: "retargeting-ads-winning-back-lost-customers",
    category: "PPC Advertising",
    author: "Admin",
    date: "10 Apr 2025",
    title: "Retargeting Ads: Winning Back Lost Customers",
    description: "Re-engage visitors with smart PPC retargeting strategies...",
    summary: "Re-engage visitors with smart PPC retargeting strategies...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/ppc.jpg",
  },
  {
    id: "evergreen-content-a-long-term-strategy",
    category: "Content Marketing",
    author: "Admin",
    date: "15 Apr 2025",
    title: "Evergreen Content: A Long-Term Strategy",
    description: "Create timeless content that drives traffic year after year...",
    summary: "Create timeless content that drives traffic year after year...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "the-power-of-user-generated-content",
    category: "Digital Marketing",
    author: "Admin",
    date: "20 Apr 2025",
    title: "The Power of User-Generated Content",
    description: "Leverage customer content to build trust and authenticity...",
    summary: "Leverage customer content to build trust and authenticity...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "mobile-first-indexing-what-you-need-to-know",
    category: "SEO",
    author: "Admin",
    date: "25 Apr 2025",
    title: "Mobile-First Indexing: What You Need to Know",
    description: "Optimize your site for Google’s mobile-first approach...",
    summary: "Optimize your site for Google’s mobile-first approach...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "creating-viral-campaigns-on-twitter",
    category: "Social Media Marketing",
    author: "Admin",
    date: "01 May 2025",
    title: "Creating Viral Campaigns on Twitter",
    description: "Craft tweets that resonate and spread like wildfire...",
    summary: "Craft tweets that resonate and spread like wildfire...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "segmentation-secrets-for-email-success",
    category: "Email Marketing",
    author: "Admin",
    date: "05 May 2025",
    title: "Segmentation Secrets for Email Success",
    description: "Target the right audience with tailored email lists...",
    summary: "Target the right audience with tailored email lists...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
  {
    id: "tracking-roi-with-advanced-analytics-tools",
    category: "Analytics",
    author: "Admin",
    date: "10 May 2025",
    title: "Tracking ROI with Advanced Analytics Tools",
    description: "Measure your marketing success with the latest analytics platforms...",
    summary: "Measure your marketing success with the latest analytics platforms...",
    image: "https://jaikvik.com/lab/new-post-video/img/blog/blog.png",
  },
];

export default blogs;